### ISSUE TITLE
録画コマンドについて

### ISSUE THREAD

**Issue by stu2005** [Harekaze/docker.harekaze.mirakurun#1]
mirakurun をdockerで運用した場合に、`/usr/local/mirakurun/opt/` にrecpt1等録画コマンドをコピーするとコンテナ内でそのコマンドが使用できる状態になりますが、当アドオンでもそれは可能でしょうか。

**Comment by mzyy94** [comment]
optは`~/.kodi/userdata/addon_data/docker.harekaze.mirakurun/opt`にマウントされているので、そちらに配置いただくことで利用可能かと思います。
